import { safeFontFamily, safeFontWeight, safeLineHeight, safeTokenKey, safeTokenValue, safeTypeScale, safeUrl } from './css-sanitizers';
import { PER_COMPONENT_MAPPING, PER_COMPONENT_SELECTOR } from './generate-css-mapping';

import type { AllOverrides } from './types';
import type { BrandConfig } from '../lib/types';

/**
 * Pure CSS generator for UXM Studio overrides.
 *
 * Single source of truth (R5): the modo Hono `/api/uxm/save` route imports
 * `generateOverridesCss` from here instead of keeping its own copy. No Node
 * APIs — runs in browser (client export) and server alike.
 *
 * Emits a stylesheet from per-component style overrides plus brand config
 * (font, logo/icon URLs, brand token blocks). All attacker-controlled brand
 * values are sanitised before interpolation because the output is served to
 * every browser session.
 */

const BRAND_FONT_WEIGHTS = 'wght@400;500;600;700';

export function fontFileUrl(fontFamily: string): string {
  const encoded = fontFamily.trim().replace(/\s+/g, '+');
  return `https://fonts.googleapis.com/css2?family=${encoded}:${BRAND_FONT_WEIGHTS}&display=swap`;
}

const REAL_CSS_PROPS = new Set([
  'background', 'backgroundColor',
  'color',
  'border', 'borderColor', 'borderRadius', 'borderWidth', 'borderStyle',
  'padding', 'paddingX', 'paddingY', 'margin',
  'gap', 'rowGap', 'columnGap',
  'width', 'height', 'minWidth', 'maxWidth', 'minHeight', 'maxHeight',
  'fontSize', 'fontWeight', 'fontFamily', 'lineHeight',
  'opacity',
  'cursor', 'display', 'position', 'overflow', 'direction',
]);

function toCSS(key: string, componentId: string): string {
  const componentMapping = PER_COMPONENT_MAPPING[componentId];
  if (componentMapping?.[key]) return componentMapping[key];

  const mapping: Record<string, string> = {
    paddingX: 'padding-inline',
    paddingY: 'padding-block',
  };
  if (mapping[key]) return mapping[key];

  const kebab = key.replace(/([A-Z])/g, '-$1').toLowerCase();
  if (REAL_CSS_PROPS.has(key)) return kebab;
  return `--uxm-${componentId}-${kebab}`;
}

function formatValue(value: string | number | boolean, key: string): string {
  if (typeof value === 'boolean') return value ? '1' : '0';
  if (typeof value === 'number') {
    // `lineHeight` is a ratio, not a length — without it here a knob saved as
    // 1.5 emits `line-height: 1.5px`, which collapses every line box.
    const unitless = ['fontWeight', 'titleWeight', 'nameWeight', 'typeLabelWeight', 'lineHeight', 'shadow', 'disabledOpacity'];
    // `opacity` is always unitless — match every *Opacity knob (e.g. the
    // per-element `itemDisabledOpacity` / `optionDisabledOpacity` variants)
    // so a saved value never gets a spurious `px` suffix.
    if (unitless.includes(key) || key.endsWith('Opacity')) return String(value);
    return `${value}px`;
  }
  // String style-override values are user/attacker-controlled and persisted
  // to a stylesheet served to every browser session — sanitise the same way
  // as brand token values so one can't break out of the declaration (e.g.
  // `red; } body{display:none}/*`). An unsafe value is dropped to '' rather
  // than throwing, so a single bad override can't blank the whole rule.
  return safeTokenValue(value) ?? '';
}

// The sanitizers moved to ./css-sanitizers.ts; they stay part of this module's
// public surface (`@viax/uxm/studio/generate-css`, brand-*-styles.tsx).
export { safeFontFamily, safeFontWeight, safeLineHeight, safeTokenKey, safeTokenValue, safeTypeScale } from './css-sanitizers';

// The three heading roles, in one place. Both the publish path below and the
// live mirror (`brand-font-styles.tsx`) derive their emitted var names from
// `role` by interpolation, so a rename here reaches both — keeping these in two
// hand-maintained lists is how `--type-${role}-font` silently drifts away from
// the names the stylesheets actually read.
export const TYPE_ROLES = [
  { role: 'display', family: 'displayFontFamily', weight: 'displayFontWeight', scale: 'displayScale' },
  { role: 'page-title', family: 'pageTitleFontFamily', weight: 'pageTitleFontWeight', scale: 'pageTitleScale' },
  { role: 'section-title', family: 'sectionTitleFontFamily', weight: 'sectionTitleFontWeight', scale: 'sectionTitleScale' },
] as const satisfies ReadonlyArray<{
  role: string;
  family: keyof BrandConfig;
  weight: keyof BrandConfig;
  scale: keyof BrandConfig;
}>;

/** Sanitised per-role typography, shared by the generator and the live mirror. */
export function resolveTypeRoles(brand: BrandConfig) {
  return TYPE_ROLES.map((r) => ({
    role: r.role,
    family: safeFontFamily(brand[r.family]),
    weight: safeFontWeight(brand[r.weight]),
    scale: safeTypeScale(brand[r.scale]),
  }));
}

/** Generate the overrides stylesheet from style overrides + brand config. */
export function generateOverridesCss(allOverrides: AllOverrides, brand: BrandConfig): string {
  const lines: string[] = ['/* Auto-generated by UXM — do not edit manually */', ''];

  const fontFamily = safeFontFamily(brand.fontFamily);
  const headingFontFamily = safeFontFamily(brand.headingFontFamily);
  const headingFontWeight = safeFontWeight(brand.headingFontWeight);
  // Per-role refinements, layered under the umbrella heading vars above.
  const roles = resolveTypeRoles(brand);
  const typeScale = safeTypeScale(brand.typeScale);
  const bodyLineHeight = safeLineHeight(brand.bodyLineHeight);
  const logoUrl = safeUrl(brand.logoUrl);
  const iconUrl = safeUrl(brand.iconUrl);
  const logoUrlDark = safeUrl(brand.logoUrlDark);
  const iconUrlDark = safeUrl(brand.iconUrlDark);

  if (fontFamily) {
    lines.push(`@import url("${fontFileUrl(fontFamily)}");`);
    lines.push('');
  }
  // Second font file only when the heading face is actually a different family
  // — picking the same one for both is a no-op, not a reason to fetch twice.
  if (headingFontFamily && headingFontFamily !== fontFamily) {
    lines.push(`@import url("${fontFileUrl(headingFontFamily)}");`);
    lines.push('');
  }
  // A role may pick a face neither the body nor the umbrella uses — fetch each
  // distinct one exactly once (@import must stay above the rules below).
  const imported = new Set([fontFamily, headingFontFamily].filter(Boolean));
  for (const { family } of roles) {
    if (family && !imported.has(family)) {
      imported.add(family);
      lines.push(`@import url("${fontFileUrl(family)}");`);
      lines.push('');
    }
  }

  const brandRules: string[] = [];
  if (fontFamily) {
    brandRules.push(`  --brand-font: "${fontFamily}", var(--font-inter), system-ui, sans-serif;`);
  }
  // Heading vars are consumed by the components' own two-layer fallbacks (see
  // e.g. page-header.scss), so there is no `body` rule and no `!important`:
  // an unset var simply lets each component's own default paint.
  if (headingFontFamily) {
    brandRules.push(`  --brand-heading-font: "${headingFontFamily}", var(--font-inter), system-ui, sans-serif;`);
  }
  if (headingFontWeight) {
    brandRules.push(`  --brand-heading-weight: ${headingFontWeight};`);
  }
  // Role vars sit between the component var and the umbrella in each atom's
  // chain, so an unset role simply falls through to the umbrella.
  for (const { role, family, weight, scale } of roles) {
    if (family) {
      brandRules.push(`  --type-${role}-font: "${family}", var(--font-inter), system-ui, sans-serif;`);
    }
    if (weight) brandRules.push(`  --type-${role}-weight: ${weight};`);
    if (scale) brandRules.push(`  --type-${role}-scale: ${scale};`);
  }
  if (typeScale) brandRules.push(`  --type-scale: ${typeScale};`);
  if (bodyLineHeight) brandRules.push(`  --type-body-line-height: ${bodyLineHeight};`);
  if (logoUrl) brandRules.push(`  --brand-logo-url: url("${logoUrl}");`);
  if (iconUrl) brandRules.push(`  --brand-icon-url: url("${iconUrl}");`);

  if (brandRules.length > 0) {
    lines.push(':root {');
    lines.push(...brandRules);
    lines.push('}');
    lines.push('');
    if (fontFamily) {
      lines.push('body { font-family: var(--brand-font) !important; }');
      lines.push('');
    }
    // Emitted ONLY when set. The library ships no element-level rules at all,
    // so an unconditional `body { line-height }` would reflow the host's own
    // content — same reasoning as the font-family rule above.
    if (bodyLineHeight) {
      // Explicit fallback: if the var is later cancelled (the studio mirror
      // re-declares it as `initial` on revert) a bare `var()` would be invalid
      // at computed-value time and `line-height` — being inherited — would
      // resolve to the parent's value, silently replacing whatever the host
      // had set on `body`. `normal` makes the wind-down state deliberate.
      lines.push(`body { line-height: var(--type-body-line-height, normal); }`);
      lines.push('');
    }
  }

  const darkBrandRules: string[] = [];
  if (logoUrlDark) darkBrandRules.push(`  --brand-logo-url: url("${logoUrlDark}");`);
  if (iconUrlDark) darkBrandRules.push(`  --brand-icon-url: url("${iconUrlDark}");`);
  if (darkBrandRules.length > 0) {
    lines.push('[data-theme="dark"] {');
    lines.push(...darkBrandRules);
    lines.push('}');
    lines.push('');
  }

  const emitTokens = (selector: string, overrides: Record<string, string> | undefined) => {
    if (!overrides) return;
    const safeEntries = Object.entries(overrides).flatMap(([k, v]) => {
      if (!safeTokenKey(k)) return [];
      const safeValue = safeTokenValue(v);
      return safeValue === undefined ? [] : [[k, safeValue] as const];
    });
    if (safeEntries.length === 0) return;
    lines.push(`${selector} {`);
    for (const [cssVar, value] of safeEntries) {
      lines.push(`  ${cssVar}: ${value};`);
    }
    lines.push('}');
    lines.push('');
  };
  // Scope customized light-mode color tokens to non-dark. `:root` and
  // `[data-theme="dark"]` carry equal specificity, so an unconditional
  // `:root` block would win over this stylesheet's own dark block for any
  // token NOT also customized for dark (equal specificity, later source
  // order) — pinning that token to its light value in dark mode too. Scoping
  // lets an unset dark token fall through the cascade to tokens/index.css's
  // own `[data-theme="dark"]` default instead.
  emitTokens(':root:not([data-theme="dark"])', brand.tokens?.light);
  emitTokens('[data-theme="dark"]', brand.tokens?.dark);

  const componentIds = Object.keys(allOverrides).sort();

  for (const id of componentIds) {
    const overrides = allOverrides[id];
    const entries = Object.entries(overrides);
    if (entries.length === 0) continue;

    const selector = PER_COMPONENT_SELECTOR[id] ?? `.uxm-${id}`;
    lines.push(`${selector} {`);
    for (const [key, value] of entries) {
      const cssProp = toCSS(key, id);
      const cssValue = formatValue(value, key);
      lines.push(`  ${cssProp}: ${cssValue};`);
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}
